{% set name = "pdtypes" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdtypes-{{ version }}.tar.gz
  sha256: b8595a5cbd9f1633f6a94230685aaf1d37160844048e26962e224e86229996cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry >=1.1.12
  run:
    - pandas >=1.3,<2.0
    - python >=3.7,<4.0

test:
  imports:
    - pdtypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/pdtypes
  summary: Show data types for pandas data frames in terminal and notebooks
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AhmedAliStats
